# Generated by Django 5.0.7 on 2024-07-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
    ]
