# Generated by Django 5.0.7 on 2024-07-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_options_recipe_isliked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='isLiked',
            field=models.IntegerField(default=0),
        ),
    ]
