# Generated by Django 5.0.7 on 2024-07-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_isliked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
    ]
