# Generated by Django 5.0.7 on 2024-07-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_recipe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.TextField(default='SvoT77', editable=False, primary_key=True, serialize=False),
        ),
    ]
