# Generated by Django 5.0.7 on 2024-07-15 18:36

import note.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_date_updated_note_recipe_alter_note_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
        migrations.AddField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(default=note.models.get_default_date_created),
        ),
    ]
