# Generated by Django 5.0.7 on 2024-07-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_remove_note_date_note_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
